#!/bin/bash

rm -f cortadoout/*.s
rm -f cortadoout/*.o
rm -f cortadoout/*.class
rm -f cortadoout/*.j
rm -f cortadoout/*.out

java -cp mjc.jar:lib/JFlex.jar:lib/java-cup-11a.jar mjc.JVMMain $1 -S
# filename=$( basename $1 )
# filename=$( basename $filename .java)
#
dir=$( dirname $1 )
mkdir -p cortadoout/$dir 2> /dev/null
mv *.j cortadoout/$dir
java -jar lib/jasmin.jar cortadoout/$dir/*.j -d cortadoout/$dir
# java -cp cortadoout/ ${filename}

#as cortadoout/${filename}.s -o cortadoout/${filename}.o

#gcc -g cortadoout/${filename}.o -o cortadoout/${filename}.out -L lib/ -lminijava

#cortadoout/${filename}.out
