#!/bin/bash

TEST_DIR=student-tests-2012
CORTADO=./cortado
COMPILE_DIRS=$(ls $TEST_DIR/compile)
EXECUTE_DIRS=$(ls $TEST_DIR/execute)
NONCOMPILE_DIRS=$(ls $TEST_DIR/noncompile)
NONEXECUTE_DIRS=$(ls $TEST_DIR/nonexecute)

# Testing files that should be possible to compile
for CUR_DIR in $COMPILE_DIRS
do
	FILES=$(ls $TEST_DIR/compile/$CUR_DIR)
	for CUR_FILE in $FILES
	do
		# Skipping files with MiniJava extensions
		EXTENSIONS=$(cat $TEST_DIR/compile/$CUR_DIR/$CUR_FILE | egrep "[[:space:]]*//[[:space:]]*EXT")
		if [ "$EXTENSIONS" != "" ]; then
			continue
		fi
		echo -n "Compiling: " $CUR_FILE"..."
		$CORTADO $TEST_DIR/compile/$CUR_DIR/$CUR_FILE > /dev/null 2> /dev/null
		if [ "$?" = 0 ]; then
			echo "OK!"
		else
			echo "FAIL!"
		fi
	done
done

# Testing files that should NOT be possible to compile
for CUR_DIR in $COMPILE_DIRS
do
	FILES=$(ls $TEST_DIR/noncompile/$CUR_DIR)
	for CUR_FILE in $FILES
	do
		# Skipping files with MiniJava extensions
		EXTENSIONS=$(cat $TEST_DIR/noncompile/$CUR_DIR/$CUR_FILE | egrep "[[:space:]]*//[[:space:]]*EXT")
		if [ "$EXTENSIONS" != "" ]; then
			continue
		fi
		echo -n "Compiling: " $CUR_FILE"..."
		$CORTADO $TEST_DIR/compile/$CUR_DIR/$CUR_FILE > /dev/null 2> /dev/null
		if [ "$?" != 0 ]; then
			echo "OK!"
		else
			echo "FAIL!"
		fi
	done
done
