#! /bin/sh

compdir="$1"

if [ ! -d "$compdir" ]
  then
    echo "error: compiler directory \"$compdir\" not found."
    echo usage: $0 [COMPILER-SOURCE-DIR]
    exit 1
  fi

cd $compdir

if [ -f build.xml ] && [ -f DESC ] && [ -d src ] && [ -d lib ]
  then true
  else
    echo "error: missing files in \"$compdir\"."
    exit
  fi

if uuencode x </dev/null >/dev/null
  then true
  else
    echo "error: The program \"uuencode\" is missing."
    echo "       Please install GNU package sharutils."
    exit 1
  fi

tmpdir="tmpVSCDtk/"
rm -rf $tmpdir
mkdir $tmpdir

cp -r build.xml $tmpdir
cp -r DESC $tmpdir
cp -r src $tmpdir
cp -r lib $tmpdir
cp -r README $tmpdir
cp -r docs/report/Report.pdf $tmpdir/report.pdf

tar cf - $tmpdir | gzip | uuencode x > submission.txt


exit 0
